name: Test Installer Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  TST_COMPANY_DOMAIN: tst.tech
  TST_ELECTRON_APP_NAME: TSTemplate
  TST_ELECTRON_GH_RELEASE_REPO_OWNER: ryuichi24
  TST_ELECTRON_GH_RELEASE_REPO_NAME: ts-template
  TST_ELECTRON_PUBLISH: 0
  TST_ELECTRON_GH_RELEASE_CHANNEL: latest
  # temp
  TST_AUTO_UPDATER_RELEASE_CHANNEL: latest
  TST_ELECTRON_RELEASE_VERSION: 0.0.0
  # see: https://github.com/AndrewEQ/electron-builder/commit/abea7ed7f32dc64bd5a6cda826685fde0832b489
  # write access token just to use to publish the installers to GitHub Releases
  GITHUB_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}

jobs:
  build-installer:
    strategy:
      matrix:
        os: [macos-14, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    outputs:
      arm-mac-installer-url: ${{ steps.upload-arm-mac-installer.outputs.artifact-url }}
      mac-installer-url: ${{ steps.upload-mac-installer.outputs.artifact-url }}
      windows-installer-url: ${{ steps.upload-windows-installer.outputs.artifact-url }}
      linux-installer-url: ${{ steps.upload-linux-installer.outputs.artifact-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 9.12.3

      - name: set up dynamic env vars
        if: ${{ github.event.inputs.is_private_release == 'true' && matrix.os != 'windows-latest' }}
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      # https://github.com/actions/runner-images/issues/5251#issuecomment-1071030822
      - name: set up dynamic env vars for windows
        if: ${{ github.event.inputs.is_private_release == 'true' && matrix.os == 'windows-latest' }}
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $env:GITHUB_ENV

        # NOTE: necessary for rebuilding native modules, see https://github.com/actions/runner/issues/2958
      - name: Install setuptools
        if: ${{ matrix.os != 'windows-latest' && matrix.os != 'macos-14' }}
        run: |
          sudo -H pip install setuptools

        # NOTE: installing "setuptools" will not fix the issue in "macos-14" runner, downgrade the python version which has "distutils" by default
      - uses: actions/setup-python@v5
        if: ${{ matrix.os == 'macos-14' }}
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Publish release for mac
        if: matrix.os == 'macos-14'
        env:
          NODE_ENV: production
          # auto updates signing for mac app
          # see for more info: https://www.electron.build/code-signing.html
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          # it is used to login apple ID without a password
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # use Xcode to generate a certificate
          CSC_LINK: ${{ secrets.CSC_LINK }}
          # export the private key of the generated certificate from key chain, and then this pass key is generated
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
        run: |
          pnpm release:desktop

      - name: Publish releases for windows and linux
        env:
          NODE_ENV: production
        if: ${{ matrix.os == 'windows-latest' || matrix.os == 'ubuntu-latest' }}
        run: |
          pnpm release:desktop

      - name: Upload arm mac installer
        if: ${{ matrix.os == 'macos-14' }}
        id: upload-arm-mac-installer
        uses: actions/upload-artifact@v4
        with:
          name: arm64-mac-installer
          path: |
            apps/desktop/builder/release/out/${{ env.TST_ELECTRON_APP_NAME }}-${{ env.TST_ELECTRON_RELEASE_VERSION }}-arm64.dmg

      - name: Upload mac installer
        if: ${{ matrix.os == 'macos-14' }}
        id: upload-mac-installer
        uses: actions/upload-artifact@v4
        with:
          name: mac-installer
          path: |
            apps/desktop/builder/release/out/${{ env.TST_ELECTRON_APP_NAME }}-${{ env.TST_ELECTRON_RELEASE_VERSION }}.dmg

      - name: Upload Windows installer
        if: ${{ matrix.os == 'windows-latest' }}
        id: upload-windows-installer
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: |
            apps/desktop/builder/release/out/*.exe

      - name: Upload Ubuntu installer
        if: ${{ matrix.os == 'ubuntu-latest' }}
        id: upload-linux-installer
        uses: actions/upload-artifact@v4
        with:
          name: linux-installer
          path: |
            apps/desktop/builder/release/out/${{ env.TST_ELECTRON_APP_NAME }}-${{ env.TST_ELECTRON_RELEASE_VERSION }}.AppImage

  commenting-build-results:
    needs: build-installer
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Post result comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const commentBody = `

            🚀 **Installers are ready for download!**

            ## 🛠️ Installers

            | Platform    | Link                                                         |
            | ----------- | ------------------------------------------------------------ |
            | Mac (ARM)   | ${{ needs.build-installer.outputs.arm-mac-installer-url }}   |
            | Mac (Intel) | ${{ needs.build-installer.outputs.mac-installer-url }}       |
            | Windows     | ${{ needs.build-installer.outputs.windows-installer-url }}   |
            | Linux       | ${{ needs.build-installer.outputs.linux-installer-url }}     |

            This build includes new changes from a commit: ${{ github.event.pull_request.head.sha }} authored by @${{ github.event.pull_request.head.user.login }}.

            🔗 [View pipeline logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: commentBody
            })
